spark:
  use_sparknlp: false
  master: "spark://spark-master:7077" # "local"
  hadoop_user_name: "app_review"
  hadoop_default_fs: "hdfs://namenode:8020" # "hdfs://localhost:8020"
db:
  host: "postgres" # "localhost"
  port: 6432
  database: "app_review"
  user: "app_review"
  password: "pass"
lda:
  seed: 42
  n_topics: 5
  max_iter: 30
